### ISSUE TITLE
Install tmuxinator from Homebrew when it becomes available

### ISSUE THREAD

**Issue by chris-fran** [chris-fran/vizion#31]
Tmuxinator issue: https://github.com/tmuxinator/tmuxinator/issues/563
Homebrew issue: https://github.com/Homebrew/homebrew-core/pull/34043

**Comment by kenden** [comment]
Homebrew issue is now: https://github.com/Homebrew/homebrew-core/pull/44567

**Comment by nexeck** [comment]
PR got merged.
